export type DeckId = "A" | "B"; // which deck a control targets — the shared audio primitive
export { AudioEngine } from "./AudioEngine";
export { Deck, HOT_CUE_COUNT, PAD_MODE_SHIFT, PAD_MODE_RESERVED, type Loop, type StemView, type PadMode } from "./Deck";
export { Eq3, EQ_MIN_DB, EQ_MAX_DB, EQ_OUT_DB, EQ_BANDS, EQ_HP, EQ_LP, EQ_Q_MIN, EQ_Q_MAX, EQ_SHAPE_TYPES, EQ_SHAPE_LABELS, EQ_SHAPE_DEFAULT, type EqRoute } from "./Eq3";
export { FxRack, BaseFxDevice, type FxDevice, type FxKind, type FxParam } from "./Fx";
export { snapIndex } from "./snap";
export { DelayFx, DELAY_MAX_SECONDS } from "./DelayFx";
export { ReverbFx, REVERB_STYLES } from "./ReverbFx";
export { SaturatorFx, SAT_STYLES, type SatStyle } from "./SaturatorFx";
export { CrushFx, CRUSH_MODES, type CrushMode } from "./CrushFx";
export { ModFx, MOD_MODES, MOD_WAVES, MOD_SOURCES } from "./ModFx";
export { GateFx, GATE_SHAPES, type GateShape } from "./GateFx";
export { NoiseFx, NOISE_TYPES, type NoiseType } from "./NoiseFx";
export { CompFx, COMP_MODES, COMP_SC_SOURCES, makeMasterLimiter, type CompMode } from "./CompFx";
export { REVERB_WORKLET_SRC } from "./reverbWorklet";
export { CRUSH_WORKLET_SRC } from "./crushWorklet";
export { MOD_DELAY_WORKLET_SRC } from "./modDelayWorklet";
export { loadFxPresets, saveFxPreset, renameFxPreset, deleteFxPreset, factoryFxPresets, FACTORY_PRESETS, type FxPreset } from "./fxPresets";
export { decodeAudio } from "./decode";
export { MicInput, type MicRoute } from "./MicInput";
export { Recorder, type Take } from "./Recorder";
export { Sampler, type SampleMode, type SampleRoute, type PlayOpts } from "./Sampler";
export { getCachedTrack, setCachedTrack, getCachedMeta, dropCachedBuffer, type CachedTrack } from "./trackCache";
export { STRETCH_WORKLET_SRC } from "./stretchWorklet";
